modLoader="javafml"
loaderVersion="[3,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/thomasglasser/${github_name}/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Chickens Primordial Playables"
updateJSONURL="https://api.modrinth.com/updates/${mod_id}/forge_updates.json?neoforge=include"
displayURL="https://github.com/thomasglasser/${github_name}/wiki"
logoFile="icon.png"
credits="Created for ChickenEngineer"
authors="Thomas Glasser"
description='''A mod centered around providing an enriching animal simulation'''
#[[mixins]]
#config="${mod_id}.mixins.json"
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"